/*
 * Copyright 2026 Orion Services.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.orion.rag.infrastructure.persistence;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDateTime;

/**
 * JPA entity for the chat_messages table.
 */
@Entity
@Table(name = "chat_messages")
@Getter @Setter @ToString(exclude = {"conversation", "user"})
public class ChatMessageEntity {

    /** Unique identifier generated by the database using UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /** Session token used to group messages for anonymous (non-authenticated) flows. */
    @Column(name = "session_id")
    private String sessionId;

    /** FK to the users table; identifies the authenticated author of this message. */
    @Column(name = "user_id")
    private String userId;

    /** FK to the conversations table; groups messages under a single conversation. */
    @Column(name = "conversation_id")
    private String conversationId;

    /** Lazy-loaded parent conversation; excluded from JSON serialisation and toString. */
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "conversation_id", insertable = false, updatable = false)
    private ConversationEntity conversation;

    /** Lazy-loaded author user entity; excluded from JSON serialisation and toString. */
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", insertable = false, updatable = false)
    private UserEntity user;

    /** Full text content of the message stored as an unbounded TEXT column. */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String content;

    /** Semantic role of this message (USER, ASSISTANT or SYSTEM) stored as a string. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private MessageType type;

    /** Date and time at which the message was created; set in the constructor and by the pre-persist hook. */
    @Column(nullable = false)
    private LocalDateTime timestamp;

    /**
     * Default constructor; initialises the timestamp to the current date and time.
     */
    public ChatMessageEntity() {
        this.timestamp = LocalDateTime.now();
    }

    /**
     * JPA lifecycle callback that ensures the timestamp is populated before the first INSERT.
     */
    @PrePersist
    protected void onCreate() {
        if (timestamp == null) {
            timestamp = LocalDateTime.now();
        }
    }

    /**
     * Persistence-layer enumeration of message roles within a conversation.
     */
    public enum MessageType {
        /** Message produced by the human user. */
        USER,
        /** Message produced by the AI assistant. */
        ASSISTANT,
        /** System-level instruction or context injected into the conversation. */
        SYSTEM
    }
}
