/*
 * Copyright 2026 Orion Services.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.orion.rag.infrastructure.persistence;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OrderBy;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * JPA entity for the conversations table.
 */
@Entity
@Table(name = "conversations")
@Getter @Setter @ToString(exclude = {"messages"})
public class ConversationEntity {

    /** Unique identifier generated by the database using UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /** Human-readable title provided by the user when creating the conversation. */
    @Column(nullable = false)
    private String title;

    /** User who created and owns this conversation; loaded lazily. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "owner_id", nullable = false)
    private UserEntity owner;

    /** Date and time when the conversation row was first inserted. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /** Date and time of the most recent message or activity; updated on every change. */
    @Column(name = "last_activity", nullable = false)
    private LocalDateTime lastActivity;

    /** All messages that belong to this conversation; cascaded and ordered by timestamp. */
    @JsonIgnore
    @OneToMany(mappedBy = "conversation", cascade = CascadeType.ALL,
        orphanRemoval = true, fetch = FetchType.LAZY)
    @OrderBy("timestamp ASC")
    private Set<ChatMessageEntity> messages = new HashSet<>();

    /**
     * JPA lifecycle callback that initialises {@code createdAt} and {@code lastActivity} on first INSERT.
     */
    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
        if (lastActivity == null) {
            lastActivity = LocalDateTime.now();
        }
    }

    /**
     * JPA lifecycle callback that refreshes {@code lastActivity} on every UPDATE.
     */
    @PreUpdate
    protected void onUpdate() {
        lastActivity = LocalDateTime.now();
    }
}
