/*
 * Copyright 2026 Orion Services.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.orion.rag.infrastructure.persistence;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * JPA entity for the request_logs table.
 */
@Entity
@Table(name = "request_logs")
@Getter @Setter
public class RequestLogEntity {

    /** Unique identifier generated by the database using UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /** WhatsApp or external phone number that originated the request (nullable for REST/MCP). */
    @Column(name = "phone_number", length = 50)
    private String phoneNumber;

    /** Identifier of the user who made the request (UUID, hash or session token). */
    @Column(name = "user_id", nullable = false, length = 255)
    private String userId;

    /** Display name of the user at the time the request was received. */
    @Column(name = "user_name", length = 255)
    private String userName;

    /** E-mail of the user (available via JWT for REST; null for WhatsApp and MCP). */
    @Column(name = "email", length = 255)
    private String email;

    /** Identifier of the conversation this request belongs to (nullable for session-based flows). */
    @Column(name = "conversation_id", length = 255)
    private String conversationId;

    /** Original message text submitted by the user, stored as an unbounded TEXT column. */
    @Column(name = "user_message", nullable = false, columnDefinition = "TEXT")
    private String userMessage;

    /** Timestamp at which the user's message was received by the server. */
    @Column(name = "message_timestamp", nullable = false)
    private LocalDateTime messageTimestamp;

    /** Context passages returned by the RAG retrieval step, stored as TEXT. */
    @Column(name = "rag_result", columnDefinition = "TEXT")
    private String ragResult;

    /** Similarity score of the top RAG match (0 when no match). */
    @Column(name = "rag_score")
    private Double ragScore;

    /** Wall-clock latency of the RAG retrieval step in milliseconds. */
    @Column(name = "rag_latency_ms")
    private Long ragLatencyMs;

    /** True when the system could not find enough context and suggested human support. */
    @Column(name = "handoff_required", nullable = false)
    private boolean handoffRequired;

    /** Optional reason for human handoff (e.g., "no_context"). */
    @Column(name = "handoff_reason", columnDefinition = "TEXT")
    private String handoffReason;

    /** Full response generated by the language model (captured after streaming completes). */
    @Column(name = "llm_response", columnDefinition = "TEXT")
    private String llmResponse;

    /** Wall-clock time to receive the complete LLM response in milliseconds. */
    @Column(name = "llm_latency_ms")
    private Long llmLatencyMs;

    /** Timestamp at which this log entry was inserted into the database. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /**
     * Default constructor; initialises {@code createdAt} to the current date and time.
     */
    public RequestLogEntity() {
        this.createdAt = LocalDateTime.now();
    }
}
