/*
 * Copyright 2026 Orion Services.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.orion.rag.infrastructure.persistence;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * JPA entity for the users table.
 */
@Entity
@Table(name = "users")
@Getter @Setter @ToString(exclude = {"passwordHash", "ownedConversations"})
public class UserEntity {

    /** Unique identifier generated by the database using UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /** Login username; must be unique across all users. */
    @Column(unique = true, nullable = false)
    private String username;

    /** E-mail address; must be unique and is used as the contact identifier. */
    @Column(unique = true, nullable = false)
    private String email;

    /** Bcrypt hash of the user's local password; excluded from JSON serialisation. */
    @JsonIgnore
    @Column(name = "password_hash")
    private String passwordHash;

    /** Hash of the Orion federated user record; used to detect profile changes from the IdP. */
    @Column(name = "orion_user_hash", unique = true)
    private String orionUserHash;

    /** Date and time when the user account was first created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /** Date and time of the user's most recent successful authentication. */
    @Column(name = "last_login")
    private LocalDateTime lastLogin;

    /** All conversations owned by this user; excluded from JSON serialisation. */
    @JsonIgnore
    @OneToMany(mappedBy = "owner", cascade = CascadeType.ALL, fetch =
        FetchType.LAZY)
    private Set<ConversationEntity> ownedConversations = new HashSet<>();

    /**
     * JPA lifecycle callback that sets {@code createdAt} to the current time before the first INSERT.
     */
    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
}
