/*
 * Copyright 2026 Orion Services.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.orion.rag.domain.model;

import java.time.LocalDateTime;

/**
 * Domain representation of a request log — pure Java, no framework annotations.
 */
public class RequestLog {

    /** Unique identifier assigned by the persistence layer. */
    private String id;
    /** WhatsApp or external phone number that originated the request. */
    private String phoneNumber;
    /** Identifier of the authenticated user associated with this request. */
    private String userId;
    /** Display name of the user at the time of the request. */
    private String userName;
    /** E-mail address of the user at the time of the request. */
    private String email;
    /** Identifier of the conversation this request belongs to. */
    private String conversationId;
    /** Original message text sent by the user. */
    private String userMessage;
    /** Timestamp at which the user message was received. */
    private LocalDateTime messageTimestamp;
    /** Textual result returned by the RAG retrieval step. */
    private String ragResult;
    /** Wall-clock time in milliseconds spent on the RAG retrieval step. */
    private Long ragLatencyMs;
    /** Full response text generated by the language model. */
    private String llmResponse;
    /** Wall-clock time in milliseconds spent waiting for the LLM response. */
    private Long llmLatencyMs;
    /** Timestamp at which this log entry was persisted. */
    private LocalDateTime createdAt;

    /**
     * Default constructor; initialises {@code createdAt} to the current date and time.
     */
    public RequestLog() {
        this.createdAt = LocalDateTime.now();
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getConversationId() {
        return conversationId;
    }

    public void setConversationId(String conversationId) {
        this.conversationId = conversationId;
    }

    public String getUserMessage() {
        return userMessage;
    }

    public void setUserMessage(String userMessage) {
        this.userMessage = userMessage;
    }

    public LocalDateTime getMessageTimestamp() {
        return messageTimestamp;
    }

    public void setMessageTimestamp(LocalDateTime messageTimestamp) {
        this.messageTimestamp = messageTimestamp;
    }

    public String getRagResult() {
        return ragResult;
    }

    public void setRagResult(String ragResult) {
        this.ragResult = ragResult;
    }

    public Long getRagLatencyMs() {
        return ragLatencyMs;
    }

    public void setRagLatencyMs(Long ragLatencyMs) {
        this.ragLatencyMs = ragLatencyMs;
    }

    public String getLlmResponse() {
        return llmResponse;
    }

    public void setLlmResponse(String llmResponse) {
        this.llmResponse = llmResponse;
    }

    public Long getLlmLatencyMs() {
        return llmLatencyMs;
    }

    public void setLlmLatencyMs(Long llmLatencyMs) {
        this.llmLatencyMs = llmLatencyMs;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
