/**
 * This file contains confidential and proprietary information.
 * Unauthorized copying, distribution, or use of this file or its contents is
 * strictly prohibited.
 *
 * 2025 Rodrigo Prestes Machado. All rights reserved.
 */
package dev.rpmhub.domain.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Entity representing a logged request to the AI assistant.
 * Captures full traceability from user input through RAG retrieval to LLM response.
 *
 * @see <a href="https://github.com/orion-services/rag/issues/10">Issue #10</a>
 */
@Entity
@Table(name = "request_logs")
@Getter
@Setter
public class RequestLog {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * Phone number that originated the request (WhatsApp). Null for REST API requests.
     */
    @Column(name = "phone_number", length = 50)
    private String phoneNumber;

    /**
     * Unique internal identifier for the user (can be a hash or session id).
     */
    @Column(name = "user_id", nullable = false, length = 255)
    private String userId;

    /**
     * Unique conversation identifier (UUID). Null for legacy session-based flows.
     */
    @Column(name = "conversation_id", length = 255)
    private String conversationId;

    /**
     * The message sent by the user.
     */
    @Column(name = "user_message", nullable = false, columnDefinition = "TEXT")
    private String userMessage;

    /**
     * Timestamp of when the message was received.
     */
    @Column(name = "message_timestamp", nullable = false)
    private LocalDateTime messageTimestamp;

    /**
     * Content retrieved from the knowledge base (RAG).
     */
    @Column(name = "rag_result", columnDefinition = "TEXT")
    private String ragResult;

    /**
     * Time taken (ms) to complete the RAG retrieval.
     */
    @Column(name = "rag_latency_ms")
    private Long ragLatencyMs;

    /**
     * Final response generated by the LLM.
     */
    @Column(name = "llm_response", columnDefinition = "TEXT")
    private String llmResponse;

    /**
     * Time taken (ms) to receive the complete LLM response (only after model finishes).
     */
    @Column(name = "llm_latency_ms")
    private Long llmLatencyMs;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    public RequestLog() {
        this.createdAt = LocalDateTime.now();
    }

}
